services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    ports:
      - '8545:8545'
    command: anvil
    working_dir: /anvil
  playground:
    image: ghcr.io/trailofbits/eth-security-toolbox:nightly
    container_name: playground
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
    command: bash
    working_dir: /workspace